name: Count Python Files in Repository

on: [push]

jobs:
  count-python-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count files ending in .py
      run: |
        echo "Count number of python code lines: $(find . -name '*.py' | xargs wc -l) lines haha."
